feat(eslint-plugin-lit-a11y): interactive-supports-focus
open-wc/open-wc pull request #1869
Opened 2020-10-10 21:26 UTC by marcoswebdev

Initial structure for https://github.com/open-wc/open-wc/pull/1781 interactive-supports-focus rule

Example: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/interactive-supports-focus.md

2020-10-11 08:10 UTC, thepassle commented
Nice, this is great!

Would it be possible to add a few more test cases, and remove the unused/commented testcases? 🙏

2020-10-12 08:28 UTC, bennypowers requested changes

2020-10-12 08:28 UTC, bennypowers commented on packages/eslint-plugin-lit-a11y/lib/rules/interactive-supports-focus.js
> +const includes = require('array-includes');
We don't need this shim, 
https://node.green/#ES2016-features-Array-prototype-includes

so let's just use `Array#includes` instead, like we're doing here on L#63

2020-10-12 08:28 UTC, bennypowers commented on packages/eslint-plugin-lit-a11y/lib/rules/interactive-supports-focus.js
> +        if (
We have a helper in utils, so you can
```js
const { isHtmlTaggedTemplate } = require('../utils/isLitHtmlTemplate.js');
```
and here:
```suggestion
        if (isHtmlTaggedTemplate(node)) {
```

2020-10-12 08:28 UTC, bennypowers commented on packages/eslint-plugin-lit-a11y/lib/rules/interactive-supports-focus.js
> +                    message: `Elements with the '${role}' interactive role must be tabbable.`,
eslint has it's own interpolation feature which makes it easier to reuse messages.

this file is a good use case for messageId as well

take a look at the eslint docs:

https://eslint.org/docs/developer-guide/working-with-rules#using-message-placeholders

2020-10-14 12:27 UTC, closed without merging

2020-10-16 18:40 UTC, marcoswebdev commented
I have created a new PR where I fix your suggestions @bennypowers!